[features]
seeds = false
skip-lint = false
[programs.devnet]
be = "4d2SZCKH3YncuHA6jeXcyZqZK2JPRAnnq29HGddLxAku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "node tests/be.js"
